const input = {
	configMetaproperties: [
		{
			key: "Vimeo_Content_Rating",
			value: "required",
		},
		{
			key: "Vimeo_Hide_From_Vimeo",
			value: "required",
		},
		{
			key: "Vimeo_License",
			value: "optional",
		},
		{
			key: "Vimeo_Password",
			value: "optional",
		},
	],
	bynderMetaproperties: {
		Send_to_Vimeo: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "Send_to_Vimeo",
			label: "Send to Vimeo",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 95,
			id: "1E1E3975-A7DE-4605-BB4D6E29C9AE7CAD",
			type: "select",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		License: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "License",
			label: "License",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 136,
			id: "49A7AF24-7229-4900-A39C8A56C6198DF9",
			type: "select",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		Monday_Board: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "Monday_Board",
			label: "Monday Board",
			isApiField: 0,
			showInDuplicateView: 0,
			zindex: 17,
			id: "A5F07C43-4E23-4864-A2726A806DBDF91C",
			type: "autocomplete",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		linkrelatedfiles: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "linkrelatedfiles",
			label: "Related Package Assets",
			isApiField: 0,
			showInDuplicateView: 0,
			zindex: 729,
			id: "96A2CFAD-0237-45CA-A64B41670B3C2144",
			type: "linked_assets",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		Send_to_Sharepoint: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "Send_to_Sharepoint",
			label: "Send to Sharepoint",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 16,
			id: "5FFA2F96-77F3-46B8-94A94F48AA1FE188",
			type: "select",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		"figmage-page-id": {
			isMultiselect: 0,
			isDisplayField: 0,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 0,
			isFilterable: 0,
			name: "figmage-page-id",
			label: "Lens",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 55,
			id: "9A8C9538-4DFD-4EA7-9761F3159BBA00C8",
			type: "text",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		region: {
			isMultiselect: 1,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "region",
			label: "Regions",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 74,
			id: "DD0FFCBD-E886-432A-8872E1767E181D5D",
			type: "select",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		Monday_Item: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "Monday_Item",
			label: "Monday Item",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 18,
			id: "655C6830-C177-470A-A6A9D3FA36294423",
			type: "autocomplete",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		extension: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "extension",
			label: "File Type",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 188,
			id: "CF0B535A-6D7D-4007-A2944BF5B33497C0",
			type: "autocomplete",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 0,
		},
		Send_to_Vimeo_Status: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "Send_to_Vimeo_Status",
			label: "Send to Vimeo Status",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 90,
			id: "64116EEC-B712-43B2-ADA9F9DA43A1148F",
			type: "select",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		"figmage-node-id": {
			isMultiselect: 0,
			isDisplayField: 0,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 0,
			isFilterable: 0,
			name: "figmage-node-id",
			label: "Edited In",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 55,
			id: "D76C8E41-6FE1-4574-AD83DE39152BC415",
			type: "text",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		Workfront_Task_URL: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "Workfront_Task_URL",
			label: "Workfront Task URL",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 15,
			id: "6F5F7001-131D-4B31-ACFC373846917E40",
			type: "longtext",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		Language: {
			isMultiselect: 1,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "Language",
			label: "Language",
			isApiField: 0,
			showInDuplicateView: 0,
			zindex: 178,
			id: "731047A5-E954-44ED-AD6371E4A48E8687",
			type: "select",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		"figmage-doc-id": {
			isMultiselect: 0,
			isDisplayField: 0,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 0,
			isFilterable: 0,
			name: "figmage-doc-id",
			label: "Camera Model",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 55,
			id: "F0B52A25-863F-4876-BEFDF8E296CAEC02",
			type: "text",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		assettype: {
			isMultiselect: 1,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "assettype",
			label: "Asset Type",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 168,
			id: "FB6EA287-CAF3-4AC2-B2B90EDBB8AEC4FE",
			type: "select",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		country: {
			isMultiselect: 1,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "country",
			label: "Countries",
			isApiField: 1,
			showInDuplicateView: 0,
			labels: {
				en_US: "Countries",
			},
			zindex: 148,
			id: "1734230F-A766-4924-B1C2EAB4A1469D2C",
			type: "select2",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 1,
			isEditable: 1,
		},
		sourcelocation: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 0,
			isFilterable: 1,
			name: "sourcelocation",
			label: "Source",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 73,
			id: "6C2EA67D-9A96-4769-A743413AD87B32A9",
			type: "text",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		relatedassets: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "relatedassets",
			label: "Related Assets",
			isApiField: 0,
			showInDuplicateView: 0,
			zindex: 719,
			id: "66957907-0DB3-4AF1-A462138B00AC26B5",
			type: "linked_assets",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		Privacy_Added: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "Privacy_Added",
			label: "Privacy Added",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 2,
			id: "A27A4F26-2FD0-43C9-82D9ECA78172CF12",
			type: "select",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		Vimeo_Hide_From_Vimeo: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "Vimeo_Hide_From_Vimeo",
			label: "Vimeo Private (required for sync)",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 93,
			id: "930EE093-FFD8-4560-AC9B35FD7EC6E511",
			type: "select",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		Vimeo_Content_Rating: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "Vimeo_Content_Rating",
			label: "Vimeo Content Rating changed ( notrequired for sync)",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 94,
			id: "29CEDA56-9EB3-4A2E-B3445626311CF8E3",
			type: "select",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		desc: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "desc",
			label: "Description",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 64,
			id: "3CDA2A1F-AF7E-457C-8E4595B64BB28B16",
			type: "text",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		downloadLink: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 0,
			isFilterable: 1,
			name: "downloadLink",
			label: "Download Link",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 69,
			id: "77B98683-A921-4C0C-B0542AB4729B97EE",
			type: "longtext",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		photographer: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "photographer",
			label: "Photographer",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 65,
			id: "0A36E145-36E2-4141-A2D18C6BFE0B4B93",
			type: "text",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		Vimeo_Password: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "Vimeo_Password",
			label: "Vimeo Password",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 91,
			id: "44B836CB-852C-4558-90301806C6BAFEB7",
			type: "longtext",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		Monday_Asset: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "Monday_Asset",
			label: "Monday Asset",
			isApiField: 0,
			showInDuplicateView: 0,
			zindex: 19,
			id: "CBC634F4-C9F4-4B6C-857F00430EEAC7F2",
			type: "longtext",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		Workfront_Document_ID: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "Workfront_Document_ID",
			label: "Workfront Document ID",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 12,
			id: "370017C2-CD66-4F14-8D03B500033A3FCA",
			type: "autocomplete",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		Vimeo_License: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "Vimeo_License",
			label: "Vimeo License",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 92,
			id: "336AB0E3-D673-4D8B-BF4B7A585E94BEF4",
			type: "select",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		Workfront_Document_URL: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "Workfront_Document_URL",
			label: "Workfront Document URL",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 13,
			id: "068F318B-1EAC-4B31-9D87EC46DEEE1F22",
			type: "longtext",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		Workfront_Version_ID: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "Workfront_Version_ID",
			label: "Workfront Version ID",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 14,
			id: "BC139BC1-2D17-4B2A-BED9DEBD79ABAE50",
			type: "longtext",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		blurhash: {
			isMultiselect: 0,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 0,
			isFilterable: 1,
			name: "blurhash",
			label: "Blur Hash",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 158,
			id: "1B4E6F87-6F07-484A-BC3B68C3E4ED3D62",
			type: "select",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
		usage: {
			isMultiselect: 1,
			isDisplayField: 1,
			isMultifilter: 0,
			showInGridView: 0,
			isRequired: 0,
			showInListView: 0,
			isMainfilter: 1,
			isFilterable: 1,
			name: "usage",
			label: "Usage",
			isApiField: 1,
			showInDuplicateView: 0,
			zindex: 208,
			id: "7D7FF3F1-1348-4F01-A3FB6FB3DC2351B1",
			type: "select",
			isSearchable: 1,
			isDrilldown: 1,
			useDependencies: 0,
			isEditable: 1,
		},
	},
};

const run = function (input) {
	//  from the MPs in the DAM, return the corresponding MP object from the named str
	const findMeta = function (str) {
		let res = {};
		res[str] = input.bynderMetaproperties[str];
		return res;
	};

	// create an array, and push the MPs associated with the Vimeo connection.  return the array of MPs
	let res = [];
	res.push(findMeta("Send_to_Vimeo"), findMeta("Send_to_Vimeo_Status"));
	for (let i = 0; i < input.configMetaproperties.length; i++) {
		res.push(findMeta(input.configMetaproperties[i].key));
	}
	return res;
};

console.log(JSON.stringify(run(input), null, 2));
